<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ELearning.Core\ELearning.Core.csproj" />
    <ProjectReference Include="..\ELearning.EF\ELearning.EF.csproj" />
  </ItemGroup>

  <ItemGroup>
	<UpToDateCheckBuilt Include="wwwroot/css/tailwind.css" Set="Css" />
	<UpToDateCheckBuilt Include="tailwind.config.js" Set="Css" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Areas\Dashboard\Views\Shared\_NotificationPartial.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Instructor\" />
  </ItemGroup>
	
  <Target Name="Tailwind" BeforeTargets="Build">
    <Exec Command="npm run css:build" />
  </Target>

	<Target Name="DashboardCss" BeforeTargets="Build">
		<Exec Command="npm run dashboardcss:build" />
	</Target>
</Project>
